version: "2.3"

networks:
  1panel-network:
    external: true
services:
  jlc-bot:
    image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/jlc-bot:1.0.1
    ports:
      - 8888:8888
    networks:
      - 1panel-network
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/jlc-bot:/data
    privileged: true
    restart: unless-stopped
    container_name: jlc-bot
